apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"samba","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"samba"}},"template":{"metadata":{"labels":{"app":"samba"}},"spec":{"containers":[{"args":["mkdir -p /data/samba;\nsmbd -F --no-process-group --configfile=/etc/samba/smb.conf\n"],"command":["/bin/sh","-c"],"image":"dperson/samba","name":"samba","volumeMounts":[{"mountPath":"/data/samba","name":"samba-data"},{"mountPath":"/etc/samba/smb.conf","name":"smb-conf","subPath":"smb.conf"},{"mountPath":"/etc/samba/username.map","name":"username-map","subPath":"username.map"}]}],"volumes":[{"name":"samba-data","persistentVolumeClaim":{"claimName":"samba-pvc"}},{"configMap":{"name":"samba-config"},"name":"smb-conf"},{"configMap":{"name":"samba-config"},"name":"username-map"}]}}}}
  creationTimestamp: "2026-02-10T14:42:55Z"
  generation: 6
  name: samba
  namespace: default
  resourceVersion: "88003"
  uid: 47e27fe1-92ad-4a3f-9d98-7c72b9d12034
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: samba
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - args:
        - |
          mkdir -p /data/samba;
          smbd -F --no-process-group --configfile=/etc/samba/smb.conf
        command:
        - /bin/sh
        - -c
        image: dperson/samba
        imagePullPolicy: Always
        name: samba
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/samba
          name: samba-data
        - mountPath: /etc/samba/smb.conf
          name: smb-conf
          subPath: smb.conf
        - mountPath: /etc/samba/username.map
          name: username-map
          subPath: username.map
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: samba-data
        persistentVolumeClaim:
          claimName: samba-pvc
      - configMap:
          defaultMode: 420
          name: samba-config
        name: smb-conf
      - configMap:
          defaultMode: 420
          name: samba-config
        name: username-map
status:
  conditions:
  - lastTransitionTime: "2026-02-13T13:13:17Z"
    lastUpdateTime: "2026-02-13T13:13:17Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-02-10T14:42:55Z"
    lastUpdateTime: "2026-02-13T13:40:25Z"
    message: ReplicaSet "samba-5b6fbc6b48" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 6
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
